[project]
name = "grpc-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "protos",
    "grpcio==1.71.2",
    "protobuf==5.29.5",
    "pydub>=0.25.1",
    "transformers>=4.55.1",
    "torch>=2.8.0",
    "numpy>=2.3.2",
    "faster-whisper>=1.2.0",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
]
