packages:
  - packages/*

catalog:
  "@eslint/js": ^9.32.0
  "@grpc/grpc-js": ^1.13.4
  "@typescript-eslint/parser": ^8.39.0
  eslint: ^9.32.0
  typescript: ^5.9.2
  typescript-eslint: ^8.39.0

onlyBuiltDependencies:
  - protobufjs
