[project]
name = "uzh-masterproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "api",
    "evaluation",
    "protos",
]


[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/web", "packages/qdrant"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.8",
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
protos = { workspace = true }
api = { workspace = true }
evaluation = { workspace = true }
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
torchaudio = { index = "pytorch-cu124" }


[tool.pytest.ini_options]
pythonpath = ["packages/api"]
testpaths = ["packages/api/tests"]
