exclude = ["**/generated/py/*"]

# Set line length for both linting and formatting
line-length = 88  # You can change this to your preferred line length

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[format]
# Configure formatter to handle line wrapping
quote-style = "double"  # Optional: enforces consistent quotes
indent-style = "space"  # Optional: ensures consistent indentation
line-ending = "auto"    # Handles line endings appropriately
# Enable preview features that include more aggressive line-splitting
preview = true