exclude = ["**/generated/py/*"]

# Set line length for both linting and formatting
line-length = 88

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # Remove isort rules to eliminate conflicts
    # "I", 
]

[format]
# Configure formatter to handle line wrapping
quote-style = "double"
indent-style = "space"
line-ending = "auto"
# Keep preview mode for better formatting
preview = true