[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "protos",
    "grpcio==1.71.2",
    "protobuf==5.29.5",
    "pydub>=0.25.1",
    "transformers>=4.55.1",
    "torch>=2.8.0",
    "numpy>=2.3.2",
    "faster-whisper>=1.2.0",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Install top-level module "main.py" as an importable module
py-modules = ["main"]

[tool.setuptools.packages.find]
# Flat layout: discover packages from the current directory
where = ["."]
include = ["domain*", "persistence*", "transcriber*"]
exclude = ["tests*", "recordings*", "recordings/*", "**/__pycache__"]

[project.optional-dependencies]
# Extras for pip/uv (e.g. uv pip install -e .[test])
test = [
    "pytest>=8.0.0",
    "pytest-mock>=3.12.0",
    "pytest-asyncio>=0.23.0",
]

[dependency-groups]
# uv-specific install group: uv sync --group test
# Keeps parity with the [project.optional-dependencies].
test = [
    "pytest>=8.0.0",
    "pytest-mock>=3.12.0",
    "pytest-asyncio>=0.23.0",
]
