[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "protos",
    "grpcio==1.71.2",
    "protobuf==5.29.5",
    "pydub>=0.25.1",
    "transformers>=4.55.1",
    "torch>=2.8.0",
    "numpy>=2.3.2",
    "faster-whisper>=1.2.0",
    "qdrant-client>=1.15.1",
    "llama-cpp-python>=0.3.16",
    "huggingface-hub>=0.34.4",
    "spacy>=3.8.7",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Install top-level module "main.py" as an importable module
py-modules = ["main"]
packages = ["api", "api.domain", "api.models", "api.vector_store"]

[tool.setuptools.package-dir]
api = "."
