[project]
name = "protos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "grpcio==1.71.2",
    "protobuf==5.29.5",
]

[dependency-groups]
dev = [
    "grpcio-tools==1.71.2",
    "protoletariat>=3.3.10",
]

[tool.setuptools]
packages = ["protos", "protos.generated.py"]

[tool.setuptools.package-dir]
protos = "."
