# RAG Evaluation Configuration
# This file defines how to run comprehensive evaluation of your RAG system

dataset:
  type: "msmarco"  # msmarco | custom
  name: "msmarco-passage/train"
  sample_size: 50  # Use smaller sample for quick testing

evaluation:
  k_values: [1, 3, 5, 10]  # Top-k values for retrieval metrics
  retrieval: true           # Evaluate retrieval quality
  generation: true          # Evaluate generation quality  
  latency: true            # Evaluate system performance

rag_service:
  endpoint: "localhost:50051"  # Your RAG service endpoint
  timeout: 30                  # Request timeout in seconds

output:
  directory: "./eval_results"
  format: ["json", "csv"]

# Advanced settings
advanced:
  parallel_queries: 1      # Number of parallel query processing
  cache_results: true      # Cache intermediate results
  verbose: true           # Detailed logging
